// Code generated by protoc-gen-go. DO NOT EDIT.
// source: structs.proto

/*
Package kelips is a generated protocol buffer package.

It is generated from these files:
	structs.proto

It has these top-level messages:
	ReqResp
	Tuple
	Snapshot
*/
package kelips

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hexatype "github.com/hexablock/hexatype"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqResp struct {
	Key   []byte           `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Nodes []*hexatype.Node `protobuf:"bytes,2,rep,name=Nodes" json:"Nodes,omitempty"`
}

func (m *ReqResp) Reset()                    { *m = ReqResp{} }
func (m *ReqResp) String() string            { return proto.CompactTextString(m) }
func (*ReqResp) ProtoMessage()               {}
func (*ReqResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqResp) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReqResp) GetNodes() []*hexatype.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Tuple struct {
	Key   []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Hosts [][]byte `protobuf:"bytes,2,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
}

func (m *Tuple) Reset()                    { *m = Tuple{} }
func (m *Tuple) String() string            { return proto.CompactTextString(m) }
func (*Tuple) ProtoMessage()               {}
func (*Tuple) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Tuple) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Tuple) GetHosts() [][]byte {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type Snapshot struct {
	Groups int32            `protobuf:"varint,1,opt,name=Groups" json:"Groups,omitempty"`
	Tuples []*Tuple         `protobuf:"bytes,2,rep,name=Tuples" json:"Tuples,omitempty"`
	Nodes  []*hexatype.Node `protobuf:"bytes,3,rep,name=Nodes" json:"Nodes,omitempty"`
}

func (m *Snapshot) Reset()                    { *m = Snapshot{} }
func (m *Snapshot) String() string            { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()               {}
func (*Snapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Snapshot) GetGroups() int32 {
	if m != nil {
		return m.Groups
	}
	return 0
}

func (m *Snapshot) GetTuples() []*Tuple {
	if m != nil {
		return m.Tuples
	}
	return nil
}

func (m *Snapshot) GetNodes() []*hexatype.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqResp)(nil), "kelips.ReqResp")
	proto.RegisterType((*Tuple)(nil), "kelips.Tuple")
	proto.RegisterType((*Snapshot)(nil), "kelips.Snapshot")
}

func init() { proto.RegisterFile("structs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2e, 0x29, 0x2a,
	0x4d, 0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x4e, 0xcd, 0xc9, 0x2c,
	0x28, 0x96, 0xd2, 0x4e, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x48,
	0xad, 0x48, 0x4c, 0xca, 0xc9, 0x4f, 0xce, 0x06, 0xb3, 0x4a, 0x2a, 0x0b, 0x52, 0xf5, 0x51, 0x34,
	0x29, 0x39, 0x72, 0xb1, 0x07, 0xa5, 0x16, 0x06, 0xa5, 0x16, 0x17, 0x08, 0x09, 0x70, 0x31, 0x7b,
	0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0x98, 0x42, 0x2a, 0x5c, 0xac, 0x7e,
	0xf9, 0x29, 0xa9, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x7c, 0x7a, 0x30, 0x43, 0xf4,
	0x40, 0xc2, 0x41, 0x10, 0x49, 0x25, 0x7d, 0x2e, 0xd6, 0x90, 0xd2, 0x82, 0x9c, 0x54, 0x2c, 0x06,
	0x88, 0x70, 0xb1, 0x7a, 0xe4, 0x17, 0x97, 0x40, 0x0c, 0xe0, 0x09, 0x82, 0x70, 0x94, 0xf2, 0xb9,
	0x38, 0x82, 0xf3, 0x12, 0x0b, 0x8a, 0x33, 0xf2, 0x4b, 0x84, 0xc4, 0xb8, 0xd8, 0xdc, 0x8b, 0xf2,
	0x4b, 0x0b, 0x8a, 0xc1, 0xda, 0x58, 0x83, 0xa0, 0x3c, 0x21, 0x55, 0x2e, 0x36, 0xb0, 0xa1, 0x30,
	0xbb, 0x79, 0xf5, 0x20, 0xbe, 0xd3, 0x03, 0x8b, 0x06, 0x41, 0x25, 0x11, 0x2e, 0x64, 0xc6, 0xe3,
	0xc2, 0x24, 0x36, 0xb0, 0x5f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x11, 0x84, 0x4b,
	0x31, 0x01, 0x00, 0x00,
}
